[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solbox_contract_devnet = "D7hxGNmozyBY4T5G2YttUh8ZbErGKXZzGd5z4749on5S"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://solana-devnet.g.alchemy.com/v2/19lueaGJPUy0UruxwkNbyLrN5GycbR-x"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
